pieceGeneration:
  linePercent: 10
  minParts: 3
  maxParts: 5
  maxTries: 5

evolution:
  initialSize: 500
  tournamentSize: 5
  crossoverSize: 250
  mutationRate: 0.1
  mutationOffset: 20

piece:
  start:
    x: 120
    y: 200
  width: 200
  height: 200